<?php

/**
 * @file
 * module for
 *
 * 
 *
 * @version
 * 2011-09-17
 *
 * Code by Kai Curry [kai@sundaysenergy.com]
 * For KB KC Labs [http://labori.us]
 * 
 * @TODO: ???
 *   variable_get('enom_user', 'sundaysenergy'),
 *   variable_get('enom_pass', 'zola322'),
 *   $service->settings['default']['uid'] = "sundaysenergy";
 *   $service->settings['default']['pw'] = "zola322";
 */

module_load_include("inc", "enom", "enom.api");
module_load_include("inc", "enom", "enom.wsclient");

/**
 * Implements hook_init()
 */
function enom_init() {
}

/**
 * Implements hook_menu().
 */
function enom_menu() {
  $items = array();
  // Menu items to manage web service operations
  $items['enom'] = array(
    'title' => 'Enom Tests',
    'file'  => 'enom.pages.inc',
    'page callback'     => 'enom_page',
    'access arguments'  => array('administer web services'),
  );
  $items['enom/domains'] = array(
    'title' => 'Registered domains',
    'file'  => 'enom.pages.inc',
    'page callback'     => 'enom_domains_page_callback',
    'access arguments'  => array('administer web services'),
  );
  return $items;
}

/**
 * Implements hook_permissions()
 */
function enom_perm() {
  return array();
}

/**
 * Implement hook_domains_provider_info()
 */
function enom_domains_provider_info() {
  return array(
    'enom' => array(
      'label' => t('Enom'),
      'class' => 'EnomDomainProvider',
      'ui class' => 'EnomDomainProviderUi',
    ),
  );
}