<?php

/**
 * @file
 * Module for dynECT API
 */

module_load_include('inc', 'wsclient_dynect', 'wsclient_dynect.rules');
module_load_include('inc', 'wsclient_dynect', 'wsclient_dynect.rules_defaults');
module_load_include('inc', 'wsclient_dynect', 'wsclient_dynect.wsclient');

/**
 * Implements hook_menu()
 */
function wsclient_dynect_menu() {
  $item['admin/config/domains/dns/dynect'] = array(
    'title' => 'DynECT API settings',
    'description' =>  'Fill your information to the API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wsclient_dynect_admin_settings'),
    'file' => 'wsclient_dynect.admin.inc',
    'access arguments' => array('administer site configuration'),
  );
  $item['dynect/zone'] = array(
    'title' => 'dynECT API all zones',
    'page callback' => 'wsclient_dynect_zone',
    'file' => 'wsclient_dynect.pages.inc',
    'access arguments' => array('administer web services'),
  );
  $item['dynect/zone/%'] = array(
    'title' => 'dynECT API zone detail',
    'page callback' => 'wsclient_dynect_zone_detail',
    'page arguments' => array(2),
    'file' => 'wsclient_dynect.pages.inc',
    'access arguments' => array('administer web services'),
    'type' => MENU_CALLBACK,
  );
  $item['dynect/zone/create'] = array(
    'title' => 'dynECT API create new zones',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wsclient_dynect_create_zone_form'),
    'file' => 'wsclient_dynect.pages.inc',
    'access arguments' => array('administer web services'),
  );
  
  $item['dynect/zone/create_record'] = array(
    'title' => 'dynECT API create new record',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wsclient_dynect_create_record_form'),
    'file' => 'wsclient_dynect.pages.inc',
    'access arguments' => array('administer web services'),
  );

  return $item;
}

/**
 * Implements hook_domains_dns_provider_info()
 */
function wsclient_dynect_domains_dns_provider_info() {
  return array(
    'dynect' => array(
      'label' => t('DynECT'),
      'class' => 'DynECTDnsProvider',
      'record management' => TRUE,
    ),
  );
}

/**
 * Return record query string from record URL 
 */
function _wsclient_dynect_record_query($record) {
  $record = str_replace('/REST/', '', $record);
  $tmp = explode('/', $record);
  $record_type = $tmp[0];
  array_shift($tmp);

  return array('record_type' => $record_type, 'query' => implode('/', $tmp));
}

/**
 * Resolve DynECT Nameserver IP Address.
 */
function _wsclient_dynect_resolve_ip($domain) {
  if (preg_match('/^ns(\d)\.p(\d+)\.dynect\.net$/', $domain, $matches)) {
    $pool = array(
      1 => '208.78.70.',
      2 => '204.13.250.',
      3 => '208.78.71.',
      4 => '204.13.251.',
    );
    if (isset($pool[$matches[1]])) {
      return $pool[$matches[1]] . intval($matches[2]);
    }
  }
}
