<?php

/**
 * @file
 * Module for dynECT API
 */

module_load_include("inc", "wsclient_dynect", "wsclient_dynect.wsclient");

function wsclient_dynect_menu() {
  $item['admin/config/domains/dns/dynect'] = array(
    'title' => 'DynECT API settings',
    'description' =>  'Fill your information to the API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wsclient_dynect_admin_settings'),
    'file' => 'wsclient_dynect.admin.inc',
    'access arguments' => array('administer site configuration'),
  );
  $item['dynect/zone'] = array(
    'title' => 'dynECT API all zones',
    'page callback' => 'wsclient_dynect_zone',
    'file' => 'wsclient_dynect.pages.inc',
    'access arguments' => array('administer web services'),
  );
  $item['dynect/zone/%'] = array(
    'title' => 'dynECT API zones',
    'page callback' => 'wsclient_dynect_zone_detail',
    'page arguments' => array(2),
    'file' => 'wsclient_dynect.pages.inc',
    'access arguments' => array('administer web services'),
  );
  return $item;
}

/**
 * Implements hook_wsclient_service_load().
 */
function wsclient_dynect_wsclient_service_load($wsclient_service) {
}