<?php

/**
 * @file
 * Module for dynECT API
 */

module_load_include('inc', 'wsclient_dynect');
module_load_include('inc', 'wsclient_dynect', 'wsclient_dynect.rules');
module_load_include('inc', 'wsclient_dynect', 'wsclient_dynect.rules_defaults');
module_load_include('inc', 'wsclient_dynect', 'wsclient_dynect.wsclient');

/**
 * Implements hook_menu()
 */
function wsclient_dynect_menu() {
  $item['admin/config/domains/dns/dynect'] = array(
    'title' => 'DynECT API settings',
    'description' =>  'Fill your information to the API.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wsclient_dynect_admin_settings'),
    'file' => 'wsclient_dynect.admin.inc',
    'access arguments' => array('administer site configuration'),
  );
  $item['dynect/zone'] = array(
    'title' => 'dynECT API all zones',
    'page callback' => 'wsclient_dynect_zone',
    'file' => 'wsclient_dynect.pages.inc',
    'access arguments' => array('administer web services'),
  );
  $item['dynect/zone/%'] = array(
    'title' => 'dynECT API zone detail',
    'page callback' => 'wsclient_dynect_zone_detail',
    'page arguments' => array(2),
    'file' => 'wsclient_dynect.pages.inc',
    'access arguments' => array('administer web services'),
    'type' => MENU_CALLBACK,
  );
  $item['dynect/zone/create'] = array(
    'title' => 'dynECT API create new zones',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wsclient_dynect_create_zone_form'),
    'file' => 'wsclient_dynect.pages.inc',
    'access arguments' => array('administer web services'),
  );
  
  $item['dynect/zone/create_record'] = array(
    'title' => 'dynECT API create new record',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wsclient_dynect_create_record_form'),
    'file' => 'wsclient_dynect.pages.inc',
    'access arguments' => array('administer web services'),
  );

  return $item;
}

/**
 * Implements hook_domains_dns_provider_info()
 */
function wsclient_dynect_domains_dns_provider_info() {
  return array(
    'dynect' => array(
      'label' => t('DynECT'),
      'class' => 'DynECTDnsProvider',
      'record management' => TRUE,
    ),
  );
}
